openapi: 3.0.0
info:
  title: Payment Service API
  description: Local API documentation for the Payment microservice.
  version: 1.0.0
servers:
  - url: http://localhost:5005
    description: Standalone Payment Service Server
  - url: http://localhost:8000/api
    description: API Gateway Server

paths:
  /payments:
    get:
      tags:
        - Payment Service
      summary: Get all payments
      responses:
        '200':
          description: Successful operation
    post:
      tags:
        - Payment Service
      summary: Process a new payment
      responses:
        '201':
          description: Created
  /payments/{id}:
    get:
      tags:
        - Payment Service
      summary: Get a payment by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
    put:
      tags:
        - Payment Service
      summary: Update a payment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
    delete:
      tags:
        - Payment Service
      summary: Delete a payment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
